version: '3.3'

services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    networks:
      - net-prod
    container_name: website

  api:
    image: api-prod:v1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - net-prod
    container_name: api-prod

networks:
  net-prod:
