all:
  vars:
    ansible_user: admin
    ansible_ssh_common_arg: '-o StrictHostKeyChecking=no'


prod:
  vars:
    ansible_password: admin
    env: production
  hosts:
    client:
      ansible_host: 10.0.1.4
