apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ns-wordpress
  labels:
    role: backend
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
        app: wordpress
    spec:
      containers:
      - name: mysql
        image: mysql:8.1
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: "${password}"
        - name: MYSQL_ROOT_PASSWORD
          value: "${root_password}"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: pvc-mysql

