apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  namespace: ns-wordpress
  labels:
    types: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
