apiVersion: v1
kind: Service
metadata:
  name: nodeport-wordpress
  namespace: ns-wordpress
spec:
  selector:
    role: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008

